name: dexecve
version: "1.2.2"
homepage: https://github.com/brad-jones/dexecve
description: Replace the running process, with a POSIX execve system call.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  path: ^1.6.4
  dexeca: ^1.2.0

dev_dependencies:
  drun: ^2.0.2
  test: ^1.14.1
  pedantic: ^1.8.0
